Add support for passing secrets as text (#78)
concourse/oci-build-task pull request #88
Opened 2022-05-01 00:36 UTC by charles-dyfis-net

To preserve the existing meaning of `BUILDKIT_SECRET_`, a new `BUILDKIT_SECRETTEXT_` prefix is added, which writes content to a file before adding corresponding entry to the `BuildkitSecrets` map.

These contents are created in `buildkit-secrets/` inside the default temporary directory; since the Docker container this all happens in is transient, no need to clean them up.

See #78 for motivation.

2022-05-02 18:30 UTC, taylorsilva requested changes
We should add a test for this new env var. Let me see where that would go. I'll drop you some pointers / a test you can copy-paste from.

2022-05-02 18:35 UTC, taylorsilva commented
You can use this test as as starting point: https://github.com/concourse/oci-build-task/blob/a46d096a62aa21ed783a76e5fc62f448c62b9333/task_test.go#L253-L259

That test makes use of the test data here: https://github.com/concourse/oci-build-task/tree/master/testdata/buildkit-secret
You can probably re-use that Dockerfile. If it doesn't work out just make a new folder with a Dockerfile that works for you.

2022-05-05 16:26 UTC, charles-dyfis-net commented
@taylorsilva -- do the changes meet your expectations wrt test suite coverage?

2022-05-06 18:03 UTC, taylorsilva approved these changes
LGTM - test coverage is fine. Thanks for the PR!

2022-05-06 18:03 UTC, merged